package teste.teste;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Teste implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.math.BigInteger dsdfsd;

   private java.util.Date dsadasdadasd;

   public Teste()
   {
   }

   public java.math.BigInteger getDsdfsd()
   {
      return this.dsdfsd;
   }

   public void setDsdfsd(java.math.BigInteger dsdfsd)
   {
      this.dsdfsd = dsdfsd;
   }

   public java.util.Date getDsadasdadasd()
   {
      return this.dsadasdadasd;
   }

   public void setDsadasdadasd(java.util.Date dsadasdadasd)
   {
      this.dsadasdadasd = dsadasdadasd;
   }

   public Teste(java.math.BigInteger dsdfsd, java.util.Date dsadasdadasd)
   {
      this.dsdfsd = dsdfsd;
      this.dsadasdadasd = dsadasdadasd;
   }

}