package teste.teste;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Teste implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean xxx;

   public Teste()
   {
   }

   public java.lang.Boolean getXxx()
   {
      return this.xxx;
   }

   public void setXxx(java.lang.Boolean xxx)
   {
      this.xxx = xxx;
   }

   public Teste(java.lang.Boolean xxx)
   {
      this.xxx = xxx;
   }

}